chdir: /home/ubuntu/errbit/public
environment: production
timeout: 30
log: tmp/thin/thin.log
pid: tmp/thin/thin.pid
socket: tmp/thin.vandaproduction.sock
max_conns: 1024
max_persistent_conns: 100
require: []
wait: 30
threadpool_size: 20
servers: 1
trace: on
debug: on

