chdir: /home/ubuntu/errbit
environment: production
timeout: 30
log: log/thin.log
pid: tmp/pids/thin.pid
socket: tmp/sockets/thin.vandaproduction.sock
max_conns: 1024
max_persistent_conns: 100
require: []
wait: 30
threadpool_size: 20
servers: 1
trace: on
debug: on

