chdir: /var/www/applications/errbit 
environment: production
timeout: 30
log: /var/tmp/thin/thin.log
pid: /var/tmp//thin/thin.pid
socket: /var/tmp/tmp/thin.vandastaging.sock
max_conns: 1024
max_persistent_conns: 100
require: []
wait: 30
threadpool_size: 20
servers: 1
trace: on
debug: on

